participants:

    Calculix:
        interfaces:
        - nodes-mesh: Calculix_Mesh
          patch: load
          read-data: [Forces0]
          write-data: [Displacements0]
          
precice-config-file: ./precice-config.xml
